import turtle

xcircle = input("enter x co-ordinate")
ycircle = input("enter y co-ordinate")
radius = input("enter the radius")
xpoint = input("enter x co-ordinate for the point.")
ypoint = input("enter y co-ordinate for the point.")
xcircle = int(xcircle)
ycircle = int(ycircle)
radius = int(radius)
xpoint = int(xpoint)
ypoint = int(ypoint)

turtle.penup()
turtle.goto(xcircle, ycircle)
turtle.pendown()
turtle.begin_fill()
turtle.color("red")
turtle.circle(radius)
turtle.end_fill()

turtle.penup()
turtle.goto(xpoint, ypoint)
turtle.pendown()
turtle.begin_fill()
turtle.color("blue")
turtle.circle(3)
turtle.end_fill()
turtle.hideturtle()
turtle.done()

